language: java
rvm:
- 2.2
- jruby
addons:
  sonarcloud:
    organization: pomil
    token:
      secure: AlYlkDcMPAYPGoPR3mBUeQ
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
env:
  global:
    secure: MomoM6te5a8fY+YgTsSb1qouHkgonhD5zf00BYBOT/EQlsEzMZvU9uNR1plt4oFHGeeNZe1Jv1aTq+paz5xHko/e/zQf96dlNVIU5jxE4vhNdvkSlIoVNeW//v9s3+KMCzXPGgWTW3MgiwtkSEP0E58IxZyRJ3WcVP/D8Ah1wgegK6p/34bZSo7R/MOYfjK7xrVhhdjlBQX5z31IVinNfwoUcPw/ZgRPJ26VzJrTpqLcmMW7/6pDil/CvB0QO8rWwQm1eJXyjRs5gcp8jEGVKQBvOCtZX/2jHMkw4VTAuEvTRIATnn3Y7P3ih2Cpn/5mAV/SYJQ7SYt4WHOYiVNGwiljOPg5y2BUC3nyUdPuF4AzMGE0dNmDdwclRrf2EI3KiK4MclCkBjSyT8xhyp6aTLQftwPz+0TCdrmj1wXTXJOl9e+8KKsx2R5/kE2BcmFEN2H9ap/LCiLprzPT6UkW03wv/nzWcSbaXa1uhRPjwp2ClD72hQLyiv4fmbPYlcq1HezCRyACRGpdw42qvR8lKO/7HLjxrTRwuPcatobXEQKfftDfhhKacxezwWJRXbCEnlgx8mx+4sCP2t71yLlWUA2zLRsmFZ/NSwKqHPdjodahhP+po/8kdibDtUKKgykQHGR8RgAzTxsMFf1ApbhfPM6rE14bcp3AS9znNcA3WOs=
